name: Build and Deploy Webring

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' 

      - name: Generate static site
        run: go run ./main.go

      # - name: Run Dev Server
      #   run: go run ./devserver.go
